# Generated by Django 4.1.6 on 2023-02-15 19:03

import django.core.validators
from django.db import migrations, models
import inventario.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'permissions': [('reporte_cantidad', 'Visualizar el reporte de cantidad'), ('reporte_detalle', 'Reporte detalle de cantidades')]},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=255, validators=[inventario.validators.validation_categoria]),
        ),
        migrations.AlterField(
            model_name='product',
            name='nombre',
            field=models.CharField(max_length=255, validators=[django.core.validators.EmailValidator('el email no es valido')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[inventario.validators.validar_par]),
        ),
    ]
